# Name and metadata of your task
task_name: 'Reverie Field Compute'
author: 'Reverie Field Project'
description: 'Participate in the Reverie Field Project KOII task to earn $SONO KPL tokens. The Reverie Field Project is a Telegram mini-app game where players earn rewards by listening to sounds. This task gathers and caches player data to enhance game performance and streamline player progression. Data is fetched from the server, cached for faster access, and submitted to IPFS for validation, ensuring efficient and fair reward distribution.The bounty per round is 250 KOII, which will be divided among users who have made submissions in the last round. Telegram bot: https://t.me/NotRadioBot or @NotRadioBot. Start your journey!'
repositoryUrl: 'https://github.com/CatchTheRecord/reverie-field-compute-task' # Replace with your own repo URL
imageUrl: 'https://catchtherecord.com/files/1305644/photo-2023-07-18-15-00-20.jpg'
infoUrl: 'infoUrl'

# Task executable network: DEVELOPMENT, ARWEAVE, or IPFS
# IPFS is the default value, as the CLI automatically manages the upload process via the Koii Storage SDK.
task_executable_network: 'IPFS'

# Task audit program: Path to your executable webpack if the selected network is IPFS. In the case of DEVELOPMENT, name it as main.
task_audit_program: 'dist/main.js'

# Round time: The total duration of your task, measured in slots (with each slot approximately equal to 408ms).
round_time: 1500

# Audit window: The audit window should be greater than 1/3 of the round time.
audit_window: 600

# Submission window: The submission window should be greater than 1/3 of the round time.
submission_window: 600

# Minimum stake amount: The minimum amount of KOII that a user must stake in order to participate in the task.
minimum_stake_amount: 1.9

# Task Bounty Type: KOII, KPL
task_type: 'KPL'

# OPTIONAL (ONLY IF Task Type = KPL) : Token Mint Address, Fire Token as an example here. 
token_type: "n3Rep7GRh3jgkGXaULNu8WzfuwCC9Rcrv82mxzJMnnH"

# Total bounty amount: The total bounty amount that will be distributed to the task. (Not accepted in case of update task).
total_bounty_amount: 1000000
bounty_amount_per_round: 250

# Allowed failed distributions: Number of times re-submission is allowed for the distribution list in case of an audit.
# It is also the number of rounds submission will be kept.
allowed_failed_distributions: 3

# Space: Space in MBs for the account size, that holds the task data.
# For testing tasks this can be set to 0.1, but for production it should be set to at least 1.
space: 2

# Note that the value field in RequirementTag is optional, so it is up to you to include it or not based on your use case.
# To add more global variables and task variables, please refer to the type, value, description format shown below.

requirementsTags:
  - type: CPU
    value: '2-core'
  - type: RAM
    value: '1 GB'
  - type: STORAGE
    value: '1 GB'

# OPTIONAL variables for creating task / REQUIRED variables for updating task

# ONLY provide the task_id and migrationDescription if you are updating the task, otherwise leave blank.
# Task_id: Previous task ID.
task_id: '8XhuD4WoFZ9PVXv9RusCDtRy2NMu9rXdcLHWGPgJMxvo'

# Migration description: Provide the description for changes made in the new version of the task.
migrationDescription: 'new description'
